import type { Venue, TimetableEntry, DiscrepancyRequest, ClassRepReport, User } from '@/types';

export const mockCurrentUser: User = {
  id: 'usr_01',
  name: 'Dr. Sarah Jenkins',
  email: 's.jenkins@university.edu',
  role: 'admin',
  adminLevel: 'department',
  adminScopeId: 'dept_csc',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
};

export const mockFacilities = [
  { id: 'fac_1', name: '4K Projector' },
  { id: 'fac_2', name: 'Public Address System' },
  { id: 'fac_3', name: 'Air Conditioning' },
  { id: 'fac_4', name: 'Tiered Seating' },
  { id: 'fac_5', name: 'Smart Whiteboard' },
];

export const mockVenues: Venue[] = [
  {
    id: 'ven_1',
    name: 'Science Lecture Theatre A',
    code: 'SLT-A',
    building: 'Faculty of Science',
    capacity: 350,
    facilities: [mockFacilities[0], mockFacilities[1], mockFacilities[2], mockFacilities[3]],
    owningLevel: 'faculty',
    isAvailable: true,
  },
  {
    id: 'ven_2',
    name: 'Engineering Hall 101',
    code: 'ENG-101',
    building: 'Block B, Engineering Complex',
    capacity: 200,
    facilities: [mockFacilities[0], mockFacilities[2], mockFacilities[4]],
    owningLevel: 'department',
    isAvailable: true,
  },
  {
    id: 'ven_3',
    name: 'Social Science Auditorium',
    code: 'FSS-AUD',
    building: 'FSS Complex',
    capacity: 500,
    facilities: [mockFacilities[0], mockFacilities[1], mockFacilities[2], mockFacilities[3], mockFacilities[4]],
    owningLevel: 'school',
    isAvailable: false,
  },
  {
    id: 'ven_4',
    name: 'Computer Science Lab 2',
    code: 'CSL-02',
    building: 'Mathematical Sciences Wing',
    capacity: 75,
    facilities: [mockFacilities[0], mockFacilities[2], mockFacilities[4]],
    owningLevel: 'department',
    isAvailable: true,
  },
];

export const mockTimetableEntries: TimetableEntry[] = [
  {
    id: 'entry_101',
    courseId: 'crs_csc301',
    courseCode: 'CSC 301',
    courseTitle: 'Database Systems & Architecture',
    lecturerId: 'lec_01',
    lecturerName: 'Prof. Alan Turing',
    venueId: 'ven_1',
    venueName: 'SLT-A',
    dayOfWeek: 'Monday',
    startTime: '09:00 AM',
    endTime: '11:00 AM',
    type: 'lecture',
    recurrenceRule: 'FREQ=WEEKLY;BYDAY=MO',
    hasConflict: false,
  },
  {
    id: 'entry_102',
    courseId: 'crs_eee402',
    courseCode: 'EEE 402',
    courseTitle: 'Signal Processing & Communications',
    lecturerId: 'lec_02',
    lecturerName: 'Dr. Claude Shannon',
    venueId: 'ven_2',
    venueName: 'ENG-101',
    dayOfWeek: 'Monday',
    startTime: '11:30 AM',
    endTime: '01:30 PM',
    type: 'lecture',
    recurrenceRule: 'FREQ=WEEKLY;BYDAY=MO',
    hasConflict: true,
    conflictReason: 'Double-booked with EEE 404 Examination Sitting',
  },
  {
    id: 'entry_103',
    courseId: 'crs_mat201',
    courseCode: 'MAT 201',
    courseTitle: 'Linear Algebra & Calculus II',
    lecturerId: 'lec_03',
    lecturerName: 'Dr. Emmy Noether',
    venueId: 'ven_1',
    venueName: 'SLT-A',
    dayOfWeek: 'Tuesday',
    startTime: '08:00 AM',
    endTime: '10:00 AM',
    type: 'lecture',
    recurrenceRule: 'FREQ=WEEKLY;BYDAY=TU',
    hasConflict: false,
  },
  {
    id: 'entry_104',
    courseId: 'crs_csc305',
    courseCode: 'CSC 305',
    courseTitle: 'Operating Systems Mid-Semester Exam',
    lecturerId: 'lec_01',
    lecturerName: 'Prof. Alan Turing',
    venueId: 'ven_3',
    venueName: 'FSS-AUD',
    dayOfWeek: 'Wednesday',
    startTime: '02:00 PM',
    endTime: '05:00 PM',
    type: 'exam',
    hasConflict: false,
  },
];

export const mockDiscrepancies: DiscrepancyRequest[] = [
  {
    id: 'disc_1',
    originalEntryId: 'entry_102',
    courseCode: 'EEE 402',
    courseTitle: 'Signal Processing & Communications',
    requestedBy: 'Dr. Claude Shannon',
    requestedByRole: 'Lecturer',
    reason: 'Venue conflict with scheduled exam sitting in ENG-101',
    type: 'shift',
    requestedVenueId: 'ven_1',
    requestedVenueName: 'SLT-A',
    requestedDate: '2026-08-03',
    requestedTimeSlot: '02:00 PM - 04:00 PM',
    status: 'pending',
    createdAt: '2026-07-27T14:30:00Z',
    targetLevel: 'faculty',
  },
  {
    id: 'disc_2',
    originalEntryId: 'entry_101',
    courseCode: 'CSC 301',
    courseTitle: 'Database Systems & Architecture',
    requestedBy: 'Dr. Sarah Jenkins',
    requestedByRole: 'HOD Computer Science',
    reason: 'Guest Lecturer international flight delay',
    type: 'postponement',
    requestedDate: '2026-08-05',
    requestedTimeSlot: '10:00 AM - 12:00 PM',
    status: 'approved',
    createdAt: '2026-07-26T09:15:00Z',
    targetLevel: 'department',
  },
  {
    id: 'disc_3',
    originalEntryId: 'entry_103',
    courseCode: 'MAT 201',
    courseTitle: 'Linear Algebra',
    requestedBy: 'Student Rep Association',
    requestedByRole: 'Class Rep',
    reason: 'Faculty wide maintenance holiday',
    type: 'cancellation',
    status: 'rejected',
    createdAt: '2026-07-25T16:00:00Z',
    targetLevel: 'school',
  },
];

export const mockReports: ClassRepReport[] = [
  {
    id: 'rep_1',
    sessionId: 'sess_101',
    courseCode: 'CSC 301',
    courseTitle: 'Database Systems & Architecture',
    held: true,
    reporterName: 'David K. (300L Class Rep)',
    timestamp: '2026-07-27T11:05:00Z',
    windowExpiresAt: '2026-07-28T11:00:00Z',
  },
  {
    id: 'rep_2',
    sessionId: 'sess_102',
    courseCode: 'EEE 402',
    courseTitle: 'Signal Processing & Communications',
    held: false,
    reasonText: 'Lecturer unavailable due to overlapping departmental meeting',
    reporterName: 'Mary O. (400L Class Rep)',
    timestamp: '2026-07-27T13:40:00Z',
    windowExpiresAt: '2026-07-28T13:30:00Z',
    lecturerResponse: 'Rescheduled for Friday 2pm pending admin approval',
  },
];
