import type {
  User,
  School,
  Faculty,
  Department,
  Venue,
  Course,
  CourseAccessGrant,
  TimetableEntry,
  LectureSession,
  ExamSitting,
  DiscrepancyRequest,
  ClassRepReport,
  UnreportedSessionFlag,
  NotificationItem,
  AuditLogEntry,
  HoldRateAnalytics,
  VenueUtilizationAnalytics,
  DiscrepancyAnalytics,
  Facility,
} from '@/types';

export const mockCurrentUser: User = {
  id: 'usr_01',
  name: 'Dr. Sarah Jenkins',
  email: 's.jenkins@university.edu',
  role: 'admin',
  identifier: 'DEPT1_ADM',
  adminLevel: 'department',
  adminScopeId: 'dept_csc',
  adminScopeName: 'Computer Science',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
};

export const mockAdmins: User[] = [
  {
    id: 'usr_01',
    name: 'Dr. Sarah Jenkins',
    email: 's.jenkins@university.edu',
    role: 'admin',
    identifier: 'DEPT1_ADM',
    adminLevel: 'department',
    adminScopeName: 'Computer Science',
    isActive: true,
  },
  {
    id: 'usr_02',
    name: 'Prof. Michael Vance',
    email: 'm.vance@university.edu',
    role: 'admin',
    identifier: 'FAC1_ADM',
    adminLevel: 'faculty',
    adminScopeName: 'Faculty of Natural Sciences',
    isActive: true,
  },
];

export const mockLecturers: User[] = [
  {
    id: 'lec_01',
    name: 'Prof. Alan Turing',
    email: 'a.turing@university.edu',
    role: 'lecturer',
    identifier: 'LEC_001',
    staffId: 'STAFF/CSC/01',
    departmentName: 'Computer Science',
    isActive: true,
  },
  {
    id: 'lec_02',
    name: 'Dr. Claude Shannon',
    email: 'c.shannon@university.edu',
    role: 'lecturer',
    identifier: 'LEC_002',
    staffId: 'STAFF/EEE/04',
    departmentName: 'Electrical Engineering',
    isActive: true,
  },
  {
    id: 'lec_03',
    name: 'Dr. Emmy Noether',
    email: 'e.noether@university.edu',
    role: 'lecturer',
    identifier: 'LEC_003',
    staffId: 'STAFF/MAT/02',
    departmentName: 'Mathematics',
    isActive: true,
  },
];

export const mockStudents: User[] = [
  {
    id: 'std_01',
    name: 'Alice Smith',
    email: 'alice@student.nsuk.edu',
    role: 'student',
    identifier: 'NSUK/CSC/2021/001',
    matricNumber: 'NSUK/CSC/2021/001',
    departmentName: 'Computer Science',
    level: 300,
    isClassRep: true,
    isActive: true,
  },
  {
    id: 'std_02',
    name: 'David Kalu',
    email: 'david@student.nsuk.edu',
    role: 'student',
    identifier: 'NSUK/CSC/2021/042',
    matricNumber: 'NSUK/CSC/2021/042',
    departmentName: 'Computer Science',
    level: 300,
    isClassRep: false,
    isActive: true,
  },
];

export const mockSchools: School[] = [
  { id: 'sch_1', name: 'Nasarawa State University', code: 'NSUK', facultiesCount: 4 },
];

export const mockFaculties: Faculty[] = [
  { id: 'fac_1', schoolId: 'sch_1', schoolName: 'Nasarawa State University', name: 'Faculty of Natural & Applied Sciences', code: 'FNS', departmentsCount: 5 },
  { id: 'fac_2', schoolId: 'sch_1', schoolName: 'Nasarawa State University', name: 'Faculty of Engineering', code: 'ENG', departmentsCount: 3 },
];

export const mockDepartments: Department[] = [
  { id: 'dept_csc', facultyId: 'fac_1', facultyName: 'Faculty of Natural & Applied Sciences', name: 'Computer Science', code: 'CSC' },
  { id: 'dept_mat', facultyId: 'fac_1', facultyName: 'Faculty of Natural & Applied Sciences', name: 'Mathematics', code: 'MAT' },
  { id: 'dept_eee', facultyId: 'fac_2', facultyName: 'Faculty of Engineering', name: 'Electrical Engineering', code: 'EEE' },
];

export const mockFacilities: Facility[] = [
  { id: 'fac_1', name: '4K Projector' },
  { id: 'fac_2', name: 'Public Address System' },
  { id: 'fac_3', name: 'Air Conditioning' },
  { id: 'fac_4', name: 'Tiered Seating' },
  { id: 'fac_5', name: 'Smart Whiteboard' },
];

export const mockVenues: Venue[] = [
  {
    id: 'ven_1',
    name: 'Lecture Theatre 1',
    code: 'LT-1',
    venueType: 'lecture_hall',
    building: 'Faculty of Science Wing',
    capacity: 350,
    examCapacity: 180,
    facilities: [mockFacilities[0], mockFacilities[1], mockFacilities[2], mockFacilities[3]],
    owningLevel: 'faculty',
    isAvailable: true,
  },
  {
    id: 'ven_2',
    name: 'Engineering Hall 101',
    code: 'ENG-101',
    venueType: 'lecture_hall',
    building: 'Engineering Block B',
    capacity: 200,
    examCapacity: 100,
    facilities: [mockFacilities[0], mockFacilities[2], mockFacilities[4]],
    owningLevel: 'department',
    owningDepartmentId: 'dept_eee',
    owningDepartmentName: 'Electrical Engineering',
    isAvailable: true,
  },
  {
    id: 'ven_3',
    name: 'Main University Auditorium',
    code: 'UNI-AUD',
    venueType: 'multipurpose',
    building: 'Central Administrative Complex',
    capacity: 800,
    examCapacity: 400,
    facilities: [mockFacilities[0], mockFacilities[1], mockFacilities[2], mockFacilities[3], mockFacilities[4]],
    owningLevel: 'school',
    isAvailable: true,
  },
  {
    id: 'ven_4',
    name: 'Computer Science Lab 2',
    code: 'CSL-02',
    venueType: 'laboratory',
    building: 'Mathematical Sciences Wing',
    capacity: 75,
    examCapacity: 40,
    facilities: [mockFacilities[0], mockFacilities[2], mockFacilities[4]],
    owningLevel: 'department',
    owningDepartmentId: 'dept_csc',
    owningDepartmentName: 'Computer Science',
    isAvailable: true,
  },
];

export const mockCourses: Course[] = [
  {
    id: 'crs_csc301',
    code: 'CSC301',
    title: 'Data Structures & Algorithms',
    level: 300,
    departmentId: 'dept_csc',
    departmentName: 'Computer Science',
    creditUnits: 3,
    owningLevel: 'department',
    lecturers: [mockLecturers[0]],
    registrationCount: 142,
  },
  {
    id: 'crs_eee402',
    code: 'EEE402',
    title: 'Signal Processing & Communications',
    level: 400,
    departmentId: 'dept_eee',
    departmentName: 'Electrical Engineering',
    creditUnits: 4,
    owningLevel: 'department',
    lecturers: [mockLecturers[1]],
    registrationCount: 88,
  },
  {
    id: 'crs_mat201',
    code: 'MAT201',
    title: 'Linear Algebra & Calculus II',
    level: 200,
    departmentId: 'dept_mat',
    departmentName: 'Mathematics',
    creditUnits: 3,
    owningLevel: 'faculty',
    lecturers: [mockLecturers[2]],
    registrationCount: 310,
  },
];

export const mockGrants: CourseAccessGrant[] = [
  {
    id: 'grant_1',
    courseId: 'crs_csc301',
    courseCode: 'CSC301',
    courseTitle: 'Data Structures & Algorithms',
    grantedToLevel: 'department',
    grantedToDepartmentId: 'dept_eee',
    grantedToDepartmentName: 'Electrical Engineering',
    direction: 'offered',
    status: 'approved',
    requestedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'grant_2',
    courseId: 'crs_mat201',
    courseCode: 'MAT201',
    courseTitle: 'Linear Algebra & Calculus II',
    grantedToLevel: 'department',
    grantedToDepartmentId: 'dept_csc',
    grantedToDepartmentName: 'Computer Science',
    direction: 'requested',
    status: 'pending',
    requestedBy: 'Dr. Sarah Jenkins',
    createdAt: '2026-07-28T14:15:00Z',
  },
];

export const mockTimetableEntries: TimetableEntry[] = [
  {
    id: 'entry_101',
    courseId: 'crs_csc301',
    courseCode: 'CSC301',
    courseTitle: 'Data Structures & Algorithms',
    lecturerId: 'lec_01',
    lecturerName: 'Prof. Alan Turing',
    venueId: 'ven_1',
    venueName: 'Lecture Theatre 1',
    dayOfWeek: 'Monday',
    startTime: '09:00:00',
    endTime: '11:00:00',
    type: 'lecture',
    academicSession: '2025/2026',
    recurrenceRule: 'weekly:tuesday',
    recurrenceStartDate: '2026-08-01',
    recurrenceEndDate: '2026-08-31',
    hasConflict: false,
  },
  {
    id: 'entry_102',
    courseId: 'crs_eee402',
    courseCode: 'EEE402',
    courseTitle: 'Signal Processing & Communications',
    lecturerId: 'lec_02',
    lecturerName: 'Dr. Claude Shannon',
    venueId: 'ven_2',
    venueName: 'Engineering Hall 101',
    dayOfWeek: 'Monday',
    startTime: '11:30:00',
    endTime: '13:30:00',
    type: 'lecture',
    academicSession: '2025/2026',
    recurrenceRule: 'weekly:monday',
    hasConflict: true,
    conflictReason: 'Venue clash with EEE404 Exam Sitting',
  },
  {
    id: 'entry_103',
    courseId: 'crs_mat201',
    courseCode: 'MAT201',
    courseTitle: 'Linear Algebra & Calculus II',
    lecturerId: 'lec_03',
    lecturerName: 'Dr. Emmy Noether',
    venueId: 'ven_1',
    venueName: 'Lecture Theatre 1',
    dayOfWeek: 'Tuesday',
    startTime: '08:00:00',
    endTime: '10:00:00',
    type: 'lecture',
    academicSession: '2025/2026',
    hasConflict: false,
  },
];

export const mockLectureSessions: LectureSession[] = [
  {
    id: 'sess_5',
    entryId: 'entry_101',
    courseCode: 'CSC301',
    courseTitle: 'Data Structures & Algorithms',
    lecturerName: 'Prof. Alan Turing',
    venueId: 'ven_1',
    venueName: 'Lecture Theatre 1',
    date: '2026-08-04',
    startTime: '09:00:00',
    endTime: '11:00:00',
    status: 'scheduled',
    hasReport: true,
  },
  {
    id: 'sess_6',
    entryId: 'entry_102',
    courseCode: 'EEE402',
    courseTitle: 'Signal Processing',
    lecturerName: 'Dr. Claude Shannon',
    venueId: 'ven_2',
    venueName: 'Engineering Hall 101',
    date: '2026-08-04',
    startTime: '11:30:00',
    endTime: '13:30:00',
    status: 'shifted',
    hasReport: false,
  },
];

export const mockExamSittings: ExamSitting[] = [
  {
    id: 'exam_1',
    timetableEntryId: 'entry_104',
    courseCode: 'CSC301',
    courseTitle: 'Data Structures & Algorithms Semester Exam',
    venueName: 'Main University Auditorium',
    date: '2026-08-20',
    startTime: '09:00:00',
    endTime: '12:00:00',
    registeredCandidatesCount: 142,
    invigilators: [mockLecturers[0], mockLecturers[2]],
  },
];

export const mockDiscrepancies: DiscrepancyRequest[] = [
  {
    id: 'disc_12',
    timetableEntryId: 'entry_102',
    lectureSessionId: 'sess_6',
    courseCode: 'EEE402',
    courseTitle: 'Signal Processing & Communications',
    requestedBy: 'Dr. Claude Shannon',
    requestedByRole: 'Lecturer',
    reason: 'Air conditioner maintenance in LT1 on Sept 14',
    requestType: 'shift_venue',
    proposedVenueId: 'ven_1',
    proposedVenueName: 'Lecture Theatre 1',
    proposedDate: '2026-08-18',
    proposedStartTime: '09:00:00',
    proposedEndTime: '11:00:00',
    status: 'pending',
    createdAt: '2026-08-02T12:00:00Z',
    targetLevel: 'faculty',
  },
  {
    id: 'disc_13',
    timetableEntryId: 'entry_101',
    courseCode: 'CSC301',
    courseTitle: 'Data Structures & Algorithms',
    requestedBy: 'Dr. Sarah Jenkins',
    requestedByRole: 'HOD Computer Science',
    reason: 'Guest Lecturer timetable collision resolved for future sessions',
    requestType: 'shift_time',
    proposedStartTime: '11:00:00',
    proposedEndTime: '13:00:00',
    status: 'approved',
    createdAt: '2026-08-01T15:30:00Z',
    targetLevel: 'department',
  },
];

export const mockReports: ClassRepReport[] = [
  {
    id: 'rep_1',
    sessionId: 'sess_5',
    courseCode: 'CSC301',
    courseTitle: 'Data Structures & Algorithms',
    held: true,
    reasonText: 'Lecture held successfully on time in LT1.',
    reporterName: 'Alice Smith (300L Rep)',
    timestamp: '2026-08-04T11:05:00Z',
    windowExpiresAt: '2026-08-04T12:00:00Z',
  },
  {
    id: 'rep_2',
    sessionId: 'sess_6',
    courseCode: 'EEE402',
    courseTitle: 'Signal Processing',
    held: false,
    reasonText: 'Lecturer arrived 35 minutes late due to faculty meeting',
    reporterName: 'Mary O. (400L Rep)',
    timestamp: '2026-08-04T13:40:00Z',
    windowExpiresAt: '2026-08-04T14:30:00Z',
    lecturerResponse: 'Class rep arrived 20 minutes late; lecture was held from 9:30 AM.',
  },
];

export const mockFlags: UnreportedSessionFlag[] = [
  {
    id: 'flag_1',
    sessionId: 'sess_8',
    courseCode: 'CSC301',
    timetableEntryTitle: 'CSC301 Weekly Lecture',
    sessionDate: '2026-07-28',
    flaggedAt: '2026-07-28T13:00:00Z',
    isAcknowledged: false,
  },
  {
    id: 'flag_2',
    sessionId: 'sess_9',
    courseCode: 'MAT201',
    timetableEntryTitle: 'MAT201 Linear Algebra',
    sessionDate: '2026-07-29',
    flaggedAt: '2026-07-29T11:00:00Z',
    isAcknowledged: true,
    acknowledgedByName: 'Dr. Sarah Jenkins',
    acknowledgedAt: '2026-07-29T14:30:00Z',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    notificationType: 'discrepancy_approved',
    title: 'Discrepancy Request Approved',
    body: 'Your shift_venue request #12 has been approved and applied.',
    relatedModel: 'DiscrepancyRequest',
    relatedId: 'disc_12',
    isRead: false,
    createdAt: '2026-08-02T12:00:00Z',
  },
  {
    id: 'notif_2',
    notificationType: 'session_shifted',
    title: 'Session Venue Shifted',
    body: 'CSC301 session on 2026-08-18 was shifted to Lecture Theatre 1.',
    relatedModel: 'LectureSession',
    relatedId: 'sess_5',
    isRead: true,
    createdAt: '2026-08-01T09:30:00Z',
  },
];

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: '42',
    actorIdentifier: 'DEPT1_ADM',
    action: 'create',
    targetModel: 'Venue',
    targetId: '3',
    beforeSnapshot: null,
    afterSnapshot: {
      id: 3,
      name: 'Audit Test Hall',
      capacity: 80,
      owning_level: 'department',
      owning_department: 1,
    },
    timestamp: '2026-08-01T18:07:00Z',
  },
  {
    id: '43',
    actorIdentifier: 'DEPT1_ADM',
    action: 'approve',
    targetModel: 'DiscrepancyRequest',
    targetId: '12',
    beforeSnapshot: { status: 'pending' },
    afterSnapshot: { status: 'approved' },
    timestamp: '2026-08-02T12:00:00Z',
  },
];

export const mockHoldRateAnalytics: HoldRateAnalytics = {
  summary: {
    totalReports: 24,
    heldCount: 20,
    notHeldCount: 4,
    holdRatePercentage: 83.33,
  },
  breakdown: [
    {
      courseId: 'crs_csc301',
      courseCode: 'CSC301',
      courseTitle: 'Data Structures & Algorithms',
      totalReports: 10,
      heldCount: 9,
      notHeldCount: 1,
      holdRatePercentage: 90.0,
    },
    {
      courseId: 'crs_eee402',
      courseCode: 'EEE402',
      courseTitle: 'Signal Processing',
      totalReports: 8,
      heldCount: 6,
      notHeldCount: 2,
      holdRatePercentage: 75.0,
    },
  ],
};

export const mockVenueUtilizationAnalytics: VenueUtilizationAnalytics = {
  summary: {
    totalVenues: 4,
    totalBookedHours: 120.5,
  },
  breakdown: [
    { venueId: 'ven_1', venueName: 'Lecture Theatre 1', totalBookedHours: 42.0, totalSessions: 21 },
    { venueId: 'ven_2', venueName: 'Engineering Hall 101', totalBookedHours: 32.0, totalSessions: 16 },
    { venueId: 'ven_3', venueName: 'Main University Auditorium', totalBookedHours: 26.5, totalSessions: 9 },
    { venueId: 'ven_4', venueName: 'Computer Science Lab 2', totalBookedHours: 20.0, totalSessions: 10 },
  ],
};

export const mockDiscrepancyAnalytics: DiscrepancyAnalytics = {
  summary: {
    totalDiscrepancies: 8,
    byStatus: { approved: 5, rejected: 2, pending: 1 },
    byRequestType: { shift_venue: 4, cancel: 2, shift_time: 2 },
  },
};
