/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as MainAuditLogsRouteImport } from './routes/_main/audit-logs'
import { Route as MainCoursesRouteImport } from './routes/_main/courses'
import { Route as MainDashboardRouteImport } from './routes/_main/dashboard'
import { Route as MainExamsRouteImport } from './routes/_main/exams'
import { Route as MainHierarchyRouteImport } from './routes/_main/hierarchy'
import { Route as MainNotificationsRouteImport } from './routes/_main/notifications'
import { Route as MainReportsRouteImport } from './routes/_main/reports'
import { Route as MainRequestsRouteImport } from './routes/_main/requests'
import { Route as MainSchedulesRouteImport } from './routes/_main/schedules'
import { Route as MainSemestersRouteImport } from './routes/_main/semesters'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainStudentsRouteImport } from './routes/_main/students'
import { Route as MainUsersRouteImport } from './routes/_main/users'
import { Route as MainVenuesRouteImport } from './routes/_main/venues'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainAuditLogsRoute = MainAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCoursesRoute = MainCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDashboardRoute = MainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainExamsRoute = MainExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainHierarchyRoute = MainHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainReportsRoute = MainReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainRequestsRoute = MainRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSchedulesRoute = MainSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSemestersRoute = MainSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStudentsRoute = MainStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUsersRoute = MainUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainVenuesRoute = MainVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/audit-logs': typeof MainAuditLogsRoute
  '/courses': typeof MainCoursesRoute
  '/dashboard': typeof MainDashboardRoute
  '/exams': typeof MainExamsRoute
  '/hierarchy': typeof MainHierarchyRoute
  '/notifications': typeof MainNotificationsRoute
  '/reports': typeof MainReportsRoute
  '/requests': typeof MainRequestsRoute
  '/schedules': typeof MainSchedulesRoute
  '/semesters': typeof MainSemestersRoute
  '/settings': typeof MainSettingsRoute
  '/students': typeof MainStudentsRoute
  '/users': typeof MainUsersRoute
  '/venues': typeof MainVenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/audit-logs': typeof MainAuditLogsRoute
  '/courses': typeof MainCoursesRoute
  '/dashboard': typeof MainDashboardRoute
  '/exams': typeof MainExamsRoute
  '/hierarchy': typeof MainHierarchyRoute
  '/notifications': typeof MainNotificationsRoute
  '/reports': typeof MainReportsRoute
  '/requests': typeof MainRequestsRoute
  '/schedules': typeof MainSchedulesRoute
  '/semesters': typeof MainSemestersRoute
  '/settings': typeof MainSettingsRoute
  '/students': typeof MainStudentsRoute
  '/users': typeof MainUsersRoute
  '/venues': typeof MainVenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_main/audit-logs': typeof MainAuditLogsRoute
  '/_main/courses': typeof MainCoursesRoute
  '/_main/dashboard': typeof MainDashboardRoute
  '/_main/exams': typeof MainExamsRoute
  '/_main/hierarchy': typeof MainHierarchyRoute
  '/_main/notifications': typeof MainNotificationsRoute
  '/_main/reports': typeof MainReportsRoute
  '/_main/requests': typeof MainRequestsRoute
  '/_main/schedules': typeof MainSchedulesRoute
  '/_main/semesters': typeof MainSemestersRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/students': typeof MainStudentsRoute
  '/_main/users': typeof MainUsersRoute
  '/_main/venues': typeof MainVenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/exams'
    | '/hierarchy'
    | '/notifications'
    | '/reports'
    | '/requests'
    | '/schedules'
    | '/semesters'
    | '/settings'
    | '/students'
    | '/users'
    | '/venues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/audit-logs'
    | '/courses'
    | '/dashboard'
    | '/exams'
    | '/hierarchy'
    | '/notifications'
    | '/reports'
    | '/requests'
    | '/schedules'
    | '/semesters'
    | '/settings'
    | '/students'
    | '/users'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_main'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_main/audit-logs'
    | '/_main/courses'
    | '/_main/dashboard'
    | '/_main/exams'
    | '/_main/hierarchy'
    | '/_main/notifications'
    | '/_main/reports'
    | '/_main/requests'
    | '/_main/schedules'
    | '/_main/semesters'
    | '/_main/settings'
    | '/_main/students'
    | '/_main/users'
    | '/_main/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/audit-logs': {
      id: '/_main/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof MainAuditLogsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/courses': {
      id: '/_main/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof MainCoursesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/dashboard': {
      id: '/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainDashboardRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/exams': {
      id: '/_main/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof MainExamsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/hierarchy': {
      id: '/_main/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof MainHierarchyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/notifications': {
      id: '/_main/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MainNotificationsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reports': {
      id: '/_main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MainReportsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/requests': {
      id: '/_main/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof MainRequestsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/schedules': {
      id: '/_main/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof MainSchedulesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/semesters': {
      id: '/_main/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof MainSemestersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/students': {
      id: '/_main/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof MainStudentsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/users': {
      id: '/_main/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainUsersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/venues': {
      id: '/_main/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof MainVenuesRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAuditLogsRoute: typeof MainAuditLogsRoute
  MainCoursesRoute: typeof MainCoursesRoute
  MainDashboardRoute: typeof MainDashboardRoute
  MainExamsRoute: typeof MainExamsRoute
  MainHierarchyRoute: typeof MainHierarchyRoute
  MainNotificationsRoute: typeof MainNotificationsRoute
  MainReportsRoute: typeof MainReportsRoute
  MainRequestsRoute: typeof MainRequestsRoute
  MainSchedulesRoute: typeof MainSchedulesRoute
  MainSemestersRoute: typeof MainSemestersRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainStudentsRoute: typeof MainStudentsRoute
  MainUsersRoute: typeof MainUsersRoute
  MainVenuesRoute: typeof MainVenuesRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuditLogsRoute: MainAuditLogsRoute,
  MainCoursesRoute: MainCoursesRoute,
  MainDashboardRoute: MainDashboardRoute,
  MainExamsRoute: MainExamsRoute,
  MainHierarchyRoute: MainHierarchyRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainReportsRoute: MainReportsRoute,
  MainRequestsRoute: MainRequestsRoute,
  MainSchedulesRoute: MainSchedulesRoute,
  MainSemestersRoute: MainSemestersRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainStudentsRoute: MainStudentsRoute,
  MainUsersRoute: MainUsersRoute,
  MainVenuesRoute: MainVenuesRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
